version: '3'
services:
    htmlizer-web:
        restart: always
        image: swiftlatex/htmlizer
        container_name: htmlizer
        depends_on:
            - redis_server
        ports:
            - 80:5001
        environment:
            REDIS_URL: redis://redis_server:6379
        volumes:
          - ~/workplace:/app/workplace
    htmlizer-worker-1:
      restart: always
      image: swiftlatex/htmlizer
      container_name: htmlizer-worker-1
      depends_on:
        - redis_server
      environment:
        REDIS_URL: redis://redis_server:6379
      command:
        python3 worker.py
      volumes:
        - ~/workplace:/app/workplace
    htmlizer-worker-2:
      restart: always
      image: swiftlatex/htmlizer
      container_name: htmlizer-worker-2
      depends_on:
        - redis_server
      environment:
        REDIS_URL: redis://redis_server:6379
      command:
        python3 worker.py
      volumes:
        - ~/workplace:/app/workplace
    htmlizer-worker-3:
      restart: always
      image: swiftlatex/htmlizer
      container_name: htmlizer-worker-3
      depends_on:
        - redis_server
      environment:
        REDIS_URL: redis://redis_server:6379
      command:
        python3 worker.py
      volumes:
        - ~/workplace:/app/workplace
    htmlizer-worker-4:
      restart: always
      image: swiftlatex/htmlizer
      container_name: htmlizer-worker-4
      depends_on:
        - redis_server
      environment:
        REDIS_URL: redis://redis_server:6379
      command:
        python3 worker.py
      volumes:
        - ~/workplace:/app/workplace
    htmlizer-cleaner:
        restart: always
        image: swiftlatex/htmlizer
        container_name: htmlizer-cleaner
        command:
          python3 cleaner.py
        volumes:
          - ~/workplace:/app/workplace
    redis_server:
        restart: always
        image: redis
        container_name: redis_server
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data

